environment:
  nodejs_version: "8.9.4"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - .\node_modules\.bin\electron-packager.cmd .\ --platform win32 --arch x64 --icon images\icon.png --out build
  - ps: Compress-Archive -Update -Path .\build\timetracker-win32-x64 -DestinationPath .\build\timetracker-win32-x64.zip
test_script:
  - node --version
  - npm --version

artifacts:
  - path: .\build\timetracker-win32-x64
    name: WindowsBuild

# Don't actually build.
build: off