environment:
  nodejs_version: "8.9.4"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - ps: powershell .\build.ps1

test_script:
  - node --version
  - npm --version

artifacts:
  - path: .\build\timetracker-win32-x64
    name: WindowsBuild

# Don't actually build.
build: on