[package]
name = "server_native"
version = "0.1.0"
authors = ["jpfeiffer16 <joepfeiffer16@gmail.com>"]

[dependencies]
rocket = "0.3.6"
rocket_codegen = "0.3.6"
rustc-serialize = "0.3"
rocket_contrib = "0.3.6"
serde = "1.0.27"
serde_derive = "1.0.27"
serde_json = "1.0.9"
serde_macros = "0.8.9"